[[commands]]
matches = "corosync-cmapctl"
output = """
config.totemconfig_reload_in_progress (u8) = 0
internal_configuration.service.0.name (str) = corosync_cmap
internal_configuration.service.0.ver (u32) = 0
internal_configuration.service.1.name (str) = corosync_cfg
internal_configuration.service.1.ver (u32) = 0
internal_configuration.service.2.name (str) = corosync_cpg
internal_configuration.service.2.ver (u32) = 0
internal_configuration.service.3.name (str) = corosync_quorum
internal_configuration.service.3.ver (u32) = 0
internal_configuration.service.4.name (str) = corosync_pload
internal_configuration.service.4.ver (u32) = 0
internal_configuration.service.5.name (str) = corosync_votequorum
internal_configuration.service.5.ver (u32) = 0
logging.debug (str) = off
logging.fileline (str) = off
logging.logfile (str) = /var/log/cluster/corosync.log
logging.logger_subsys.QUORUM.debug (str) = off
logging.logger_subsys.QUORUM.subsys (str) = QUORUM
logging.timestamp (str) = on
logging.to_logfile (str) = no
logging.to_stderr (str) = no
logging.to_syslog (str) = yes
nodelist.local_node_pos (u32) = 0
nodelist.node.0.nodeid (u32) = 1
nodelist.node.0.ring0_addr (str) = 192.168.157.10
nodelist.node.1.nodeid (u32) = 2
nodelist.node.1.ring0_addr (str) = 192.168.157.11
quorum.expected_votes (u32) = 2
quorum.provider (str) = corosync_votequorum
quorum.two_node (u8) = 1
runtime.blackbox.dump_flight_data (str) = no
runtime.blackbox.dump_state (str) = no
runtime.config.totem.block_unlisted_ips (u32) = 1
runtime.config.totem.cancel_token_hold_on_retransmit (u32) = 0
runtime.config.totem.consensus (u32) = 6000
runtime.config.totem.downcheck (u32) = 1000
runtime.config.totem.fail_recv_const (u32) = 2500
runtime.config.totem.heartbeat_failures_allowed (u32) = 0
runtime.config.totem.hold (u32) = 382
runtime.config.totem.join (u32) = 60
runtime.config.totem.max_messages (u32) = 20
runtime.config.totem.max_network_delay (u32) = 50
runtime.config.totem.merge (u32) = 200
runtime.config.totem.miss_count_const (u32) = 5
runtime.config.totem.rrp_autorecovery_check_timeout (u32) = 1000
runtime.config.totem.rrp_problem_count_mcast_threshold (u32) = 100
runtime.config.totem.rrp_problem_count_threshold (u32) = 10
runtime.config.totem.rrp_problem_count_timeout (u32) = 2000
runtime.config.totem.rrp_token_expired_timeout (u32) = 490
runtime.config.totem.send_join (u32) = 0
runtime.config.totem.seqno_unchanged_const (u32) = 30
runtime.config.totem.token (u32) = 5000
runtime.config.totem.token_retransmit (u32) = 490
runtime.config.totem.token_retransmits_before_loss_const (u32) = 10
runtime.config.totem.window_size (u32) = 50
runtime.connections.active (u64) = 12
runtime.connections.closed (u64) = 5092119
runtime.connections.corosync-cmapct:18688:0x563dc6d07d50.client_pid (u32) = 18688
runtime.connections.corosync-cmapct:18688:0x563dc6d07d50.dispatched (u64) = 0
runtime.connections.corosync-cmapct:18688:0x563dc6d07d50.flow_control (u32) = 0
runtime.connections.corosync-cmapct:18688:0x563dc6d07d50.flow_control_count (u64) = 0
runtime.connections.corosync-cmapct:18688:0x563dc6d07d50.invalid_request (u64) = 0
runtime.connections.corosync-cmapct:18688:0x563dc6d07d50.name (str) = corosync-cmapct
runtime.connections.corosync-cmapct:18688:0x563dc6d07d50.overload (u64) = 0
runtime.connections.corosync-cmapct:18688:0x563dc6d07d50.queue_size (u32) = 0
runtime.connections.corosync-cmapct:18688:0x563dc6d07d50.recv_retries (u64) = 0
runtime.connections.corosync-cmapct:18688:0x563dc6d07d50.requests (u64) = 0
runtime.connections.corosync-cmapct:18688:0x563dc6d07d50.responses (u64) = 0
runtime.connections.corosync-cmapct:18688:0x563dc6d07d50.send_retries (u64) = 0
runtime.connections.corosync-cmapct:18688:0x563dc6d07d50.service_id (u32) = 0
runtime.connections.pacemaker-attrd:2247:0x563dc6ad8cb0.client_pid (u32) = 2247
runtime.connections.pacemaker-attrd:2247:0x563dc6ad8cb0.dispatched (u64) = 26
runtime.connections.pacemaker-attrd:2247:0x563dc6ad8cb0.flow_control (u32) = 0
runtime.connections.pacemaker-attrd:2247:0x563dc6ad8cb0.flow_control_count (u64) = 0
runtime.connections.pacemaker-attrd:2247:0x563dc6ad8cb0.invalid_request (u64) = 0
runtime.connections.pacemaker-attrd:2247:0x563dc6ad8cb0.name (str) = pacemaker-attrd
runtime.connections.pacemaker-attrd:2247:0x563dc6ad8cb0.overload (u64) = 0
runtime.connections.pacemaker-attrd:2247:0x563dc6ad8cb0.queue_size (u32) = 0
runtime.connections.pacemaker-attrd:2247:0x563dc6ad8cb0.recv_retries (u64) = 0
runtime.connections.pacemaker-attrd:2247:0x563dc6ad8cb0.requests (u64) = 17
runtime.connections.pacemaker-attrd:2247:0x563dc6ad8cb0.responses (u64) = 2
runtime.connections.pacemaker-attrd:2247:0x563dc6ad8cb0.send_retries (u64) = 0
runtime.connections.pacemaker-attrd:2247:0x563dc6ad8cb0.service_id (u32) = 2
runtime.connections.pacemaker-based:2244:0x563dc6adace0.client_pid (u32) = 2244
runtime.connections.pacemaker-based:2244:0x563dc6adace0.dispatched (u64) = 4886428
runtime.connections.pacemaker-based:2244:0x563dc6adace0.flow_control (u32) = 0
runtime.connections.pacemaker-based:2244:0x563dc6adace0.flow_control_count (u64) = 0
runtime.connections.pacemaker-based:2244:0x563dc6adace0.invalid_request (u64) = 0
runtime.connections.pacemaker-based:2244:0x563dc6adace0.name (str) = pacemaker-based
runtime.connections.pacemaker-based:2244:0x563dc6adace0.overload (u64) = 0
runtime.connections.pacemaker-based:2244:0x563dc6adace0.queue_size (u32) = 0
runtime.connections.pacemaker-based:2244:0x563dc6adace0.recv_retries (u64) = 0
runtime.connections.pacemaker-based:2244:0x563dc6adace0.requests (u64) = 2068640
runtime.connections.pacemaker-based:2244:0x563dc6adace0.responses (u64) = 2
runtime.connections.pacemaker-based:2244:0x563dc6adace0.send_retries (u64) = 0
runtime.connections.pacemaker-based:2244:0x563dc6adace0.service_id (u32) = 2
runtime.connections.pacemaker-contr:2249:0x563dc6ce0920.client_pid (u32) = 2249
runtime.connections.pacemaker-contr:2249:0x563dc6ce0920.dispatched (u64) = 1
runtime.connections.pacemaker-contr:2249:0x563dc6ce0920.flow_control (u32) = 0
runtime.connections.pacemaker-contr:2249:0x563dc6ce0920.flow_control_count (u64) = 0
runtime.connections.pacemaker-contr:2249:0x563dc6ce0920.invalid_request (u64) = 0
runtime.connections.pacemaker-contr:2249:0x563dc6ce0920.name (str) = pacemaker-contr
runtime.connections.pacemaker-contr:2249:0x563dc6ce0920.overload (u64) = 0
runtime.connections.pacemaker-contr:2249:0x563dc6ce0920.queue_size (u32) = 0
runtime.connections.pacemaker-contr:2249:0x563dc6ce0920.recv_retries (u64) = 0
runtime.connections.pacemaker-contr:2249:0x563dc6ce0920.requests (u64) = 3
runtime.connections.pacemaker-contr:2249:0x563dc6ce0920.responses (u64) = 3
runtime.connections.pacemaker-contr:2249:0x563dc6ce0920.send_retries (u64) = 0
runtime.connections.pacemaker-contr:2249:0x563dc6ce0920.service_id (u32) = 3
runtime.connections.pacemaker-contr:2249:0x563dc6ce4c80.client_pid (u32) = 2249
runtime.connections.pacemaker-contr:2249:0x563dc6ce4c80.dispatched (u64) = 68
runtime.connections.pacemaker-contr:2249:0x563dc6ce4c80.flow_control (u32) = 0
runtime.connections.pacemaker-contr:2249:0x563dc6ce4c80.flow_control_count (u64) = 0
runtime.connections.pacemaker-contr:2249:0x563dc6ce4c80.invalid_request (u64) = 0
runtime.connections.pacemaker-contr:2249:0x563dc6ce4c80.name (str) = pacemaker-contr
runtime.connections.pacemaker-contr:2249:0x563dc6ce4c80.overload (u64) = 0
runtime.connections.pacemaker-contr:2249:0x563dc6ce4c80.queue_size (u32) = 0
runtime.connections.pacemaker-contr:2249:0x563dc6ce4c80.recv_retries (u64) = 0
runtime.connections.pacemaker-contr:2249:0x563dc6ce4c80.requests (u64) = 41
runtime.connections.pacemaker-contr:2249:0x563dc6ce4c80.responses (u64) = 2
runtime.connections.pacemaker-contr:2249:0x563dc6ce4c80.send_retries (u64) = 0
runtime.connections.pacemaker-contr:2249:0x563dc6ce4c80.service_id (u32) = 2
runtime.connections.pacemaker-fence:2245:0x563dc6ad81a0.client_pid (u32) = 2245
runtime.connections.pacemaker-fence:2245:0x563dc6ad81a0.dispatched (u64) = 11
runtime.connections.pacemaker-fence:2245:0x563dc6ad81a0.flow_control (u32) = 0
runtime.connections.pacemaker-fence:2245:0x563dc6ad81a0.flow_control_count (u64) = 0
runtime.connections.pacemaker-fence:2245:0x563dc6ad81a0.invalid_request (u64) = 0
runtime.connections.pacemaker-fence:2245:0x563dc6ad81a0.name (str) = pacemaker-fence
runtime.connections.pacemaker-fence:2245:0x563dc6ad81a0.overload (u64) = 0
runtime.connections.pacemaker-fence:2245:0x563dc6ad81a0.queue_size (u32) = 0
runtime.connections.pacemaker-fence:2245:0x563dc6ad81a0.recv_retries (u64) = 0
runtime.connections.pacemaker-fence:2245:0x563dc6ad81a0.requests (u64) = 7
runtime.connections.pacemaker-fence:2245:0x563dc6ad81a0.responses (u64) = 2
runtime.connections.pacemaker-fence:2245:0x563dc6ad81a0.send_retries (u64) = 0
runtime.connections.pacemaker-fence:2245:0x563dc6ad81a0.service_id (u32) = 2
runtime.connections.pacemakerd:2242:0x563dc65d0580.client_pid (u32) = 2242
runtime.connections.pacemakerd:2242:0x563dc65d0580.dispatched (u64) = 0
runtime.connections.pacemakerd:2242:0x563dc65d0580.flow_control (u32) = 0
runtime.connections.pacemakerd:2242:0x563dc65d0580.flow_control_count (u64) = 0
runtime.connections.pacemakerd:2242:0x563dc65d0580.invalid_request (u64) = 0
runtime.connections.pacemakerd:2242:0x563dc65d0580.name (str) = pacemakerd
runtime.connections.pacemakerd:2242:0x563dc65d0580.overload (u64) = 0
runtime.connections.pacemakerd:2242:0x563dc65d0580.queue_size (u32) = 0
runtime.connections.pacemakerd:2242:0x563dc65d0580.recv_retries (u64) = 0
runtime.connections.pacemakerd:2242:0x563dc65d0580.requests (u64) = 1
runtime.connections.pacemakerd:2242:0x563dc65d0580.responses (u64) = 1
runtime.connections.pacemakerd:2242:0x563dc65d0580.send_retries (u64) = 0
runtime.connections.pacemakerd:2242:0x563dc65d0580.service_id (u32) = 1
runtime.connections.pacemakerd:2242:0x563dc67d1840.client_pid (u32) = 2242
runtime.connections.pacemakerd:2242:0x563dc67d1840.dispatched (u64) = 1
runtime.connections.pacemakerd:2242:0x563dc67d1840.flow_control (u32) = 0
runtime.connections.pacemakerd:2242:0x563dc67d1840.flow_control_count (u64) = 0
runtime.connections.pacemakerd:2242:0x563dc67d1840.invalid_request (u64) = 0
runtime.connections.pacemakerd:2242:0x563dc67d1840.name (str) = pacemakerd
runtime.connections.pacemakerd:2242:0x563dc67d1840.overload (u64) = 0
runtime.connections.pacemakerd:2242:0x563dc67d1840.queue_size (u32) = 0
runtime.connections.pacemakerd:2242:0x563dc67d1840.recv_retries (u64) = 0
runtime.connections.pacemakerd:2242:0x563dc67d1840.requests (u64) = 3
runtime.connections.pacemakerd:2242:0x563dc67d1840.responses (u64) = 3
runtime.connections.pacemakerd:2242:0x563dc67d1840.send_retries (u64) = 0
runtime.connections.pacemakerd:2242:0x563dc67d1840.service_id (u32) = 3
runtime.connections.pacemakerd:2242:0x563dc67d57a0.client_pid (u32) = 2242
runtime.connections.pacemakerd:2242:0x563dc67d57a0.dispatched (u64) = 17
runtime.connections.pacemakerd:2242:0x563dc67d57a0.flow_control (u32) = 0
runtime.connections.pacemakerd:2242:0x563dc67d57a0.flow_control_count (u64) = 0
runtime.connections.pacemakerd:2242:0x563dc67d57a0.invalid_request (u64) = 0
runtime.connections.pacemakerd:2242:0x563dc67d57a0.name (str) = pacemakerd
runtime.connections.pacemakerd:2242:0x563dc67d57a0.overload (u64) = 0
runtime.connections.pacemakerd:2242:0x563dc67d57a0.queue_size (u32) = 0
runtime.connections.pacemakerd:2242:0x563dc67d57a0.recv_retries (u64) = 0
runtime.connections.pacemakerd:2242:0x563dc67d57a0.requests (u64) = 10
runtime.connections.pacemakerd:2242:0x563dc67d57a0.responses (u64) = 2
runtime.connections.pacemakerd:2242:0x563dc67d57a0.send_retries (u64) = 0
runtime.connections.pacemakerd:2242:0x563dc67d57a0.service_id (u32) = 2
runtime.connections.sbd:2240:0x563dc65c76d0.client_pid (u32) = 2240
runtime.connections.sbd:2240:0x563dc65c76d0.dispatched (u64) = 0
runtime.connections.sbd:2240:0x563dc65c76d0.flow_control (u32) = 0
runtime.connections.sbd:2240:0x563dc65c76d0.flow_control_count (u64) = 0
runtime.connections.sbd:2240:0x563dc65c76d0.invalid_request (u64) = 0
runtime.connections.sbd:2240:0x563dc65c76d0.name (str) = sbd
runtime.connections.sbd:2240:0x563dc65c76d0.overload (u64) = 0
runtime.connections.sbd:2240:0x563dc65c76d0.queue_size (u32) = 0
runtime.connections.sbd:2240:0x563dc65c76d0.recv_retries (u64) = 0
runtime.connections.sbd:2240:0x563dc65c76d0.requests (u64) = 6
runtime.connections.sbd:2240:0x563dc65c76d0.responses (u64) = 6
runtime.connections.sbd:2240:0x563dc65c76d0.send_retries (u64) = 0
runtime.connections.sbd:2240:0x563dc65c76d0.service_id (u32) = 0
runtime.connections.sbd:2240:0x563dc65ca1d0.client_pid (u32) = 2240
runtime.connections.sbd:2240:0x563dc65ca1d0.dispatched (u64) = 2
runtime.connections.sbd:2240:0x563dc65ca1d0.flow_control (u32) = 0
runtime.connections.sbd:2240:0x563dc65ca1d0.flow_control_count (u64) = 0
runtime.connections.sbd:2240:0x563dc65ca1d0.invalid_request (u64) = 0
runtime.connections.sbd:2240:0x563dc65ca1d0.name (str) = sbd
runtime.connections.sbd:2240:0x563dc65ca1d0.overload (u64) = 0
runtime.connections.sbd:2240:0x563dc65ca1d0.queue_size (u32) = 0
runtime.connections.sbd:2240:0x563dc65ca1d0.recv_retries (u64) = 0
runtime.connections.sbd:2240:0x563dc65ca1d0.requests (u64) = 2
runtime.connections.sbd:2240:0x563dc65ca1d0.responses (u64) = 2
runtime.connections.sbd:2240:0x563dc65ca1d0.send_retries (u64) = 0
runtime.connections.sbd:2240:0x563dc65ca1d0.service_id (u32) = 2
runtime.connections.sbd:2240:0x563dc65cdec0.client_pid (u32) = 2240
runtime.connections.sbd:2240:0x563dc65cdec0.dispatched (u64) = 0
runtime.connections.sbd:2240:0x563dc65cdec0.flow_control (u32) = 0
runtime.connections.sbd:2240:0x563dc65cdec0.flow_control_count (u64) = 0
runtime.connections.sbd:2240:0x563dc65cdec0.invalid_request (u64) = 0
runtime.connections.sbd:2240:0x563dc65cdec0.name (str) = sbd
runtime.connections.sbd:2240:0x563dc65cdec0.overload (u64) = 0
runtime.connections.sbd:2240:0x563dc65cdec0.queue_size (u32) = 0
runtime.connections.sbd:2240:0x563dc65cdec0.recv_retries (u64) = 0
runtime.connections.sbd:2240:0x563dc65cdec0.requests (u64) = 30545079
runtime.connections.sbd:2240:0x563dc65cdec0.responses (u64) = 30545079
runtime.connections.sbd:2240:0x563dc65cdec0.send_retries (u64) = 0
runtime.connections.sbd:2240:0x563dc65cdec0.service_id (u32) = 5
runtime.services.cfg.0.rx (u64) = 0
runtime.services.cfg.0.tx (u64) = 0
runtime.services.cfg.1.rx (u64) = 0
runtime.services.cfg.1.tx (u64) = 0
runtime.services.cfg.2.rx (u64) = 0
runtime.services.cfg.2.tx (u64) = 0
runtime.services.cfg.3.rx (u64) = 0
runtime.services.cfg.3.tx (u64) = 0
runtime.services.cfg.service_id (u16) = 1
runtime.services.cmap.0.rx (u64) = 3
runtime.services.cmap.0.tx (u64) = 2
runtime.services.cmap.service_id (u16) = 0
runtime.services.cpg.0.rx (u64) = 12
runtime.services.cpg.0.tx (u64) = 6
runtime.services.cpg.1.rx (u64) = 0
runtime.services.cpg.1.tx (u64) = 0
runtime.services.cpg.2.rx (u64) = 0
runtime.services.cpg.2.tx (u64) = 0
runtime.services.cpg.3.rx (u64) = 4886540
runtime.services.cpg.3.tx (u64) = 2068705
runtime.services.cpg.4.rx (u64) = 0
runtime.services.cpg.4.tx (u64) = 0
runtime.services.cpg.5.rx (u64) = 3
runtime.services.cpg.5.tx (u64) = 2
runtime.services.cpg.6.rx (u64) = 0
runtime.services.cpg.6.tx (u64) = 0
runtime.services.cpg.service_id (u16) = 2
runtime.services.pload.0.rx (u64) = 0
runtime.services.pload.0.tx (u64) = 0
runtime.services.pload.1.rx (u64) = 0
runtime.services.pload.1.tx (u64) = 0
runtime.services.pload.service_id (u16) = 4
runtime.services.quorum.service_id (u16) = 3
runtime.services.votequorum.0.rx (u64) = 7
runtime.services.votequorum.0.tx (u64) = 4
runtime.services.votequorum.1.rx (u64) = 0
runtime.services.votequorum.1.tx (u64) = 0
runtime.services.votequorum.2.rx (u64) = 0
runtime.services.votequorum.2.tx (u64) = 0
runtime.services.votequorum.3.rx (u64) = 0
runtime.services.votequorum.3.tx (u64) = 0
runtime.services.votequorum.service_id (u16) = 5
runtime.totem.pg.mrp.rrp.0.faulty (u8) = 0
runtime.totem.pg.mrp.srp.avg_backlog_calc (u32) = 0
runtime.totem.pg.mrp.srp.avg_token_workload (u32) = 0
runtime.totem.pg.mrp.srp.commit_entered (u64) = 2
runtime.totem.pg.mrp.srp.commit_token_lost (u64) = 0
runtime.totem.pg.mrp.srp.consensus_timeouts (u64) = 0
runtime.totem.pg.mrp.srp.continuous_gather (u32) = 0
runtime.totem.pg.mrp.srp.continuous_sendmsg_failures (u32) = 0
runtime.totem.pg.mrp.srp.firewall_enabled_or_nic_failure (u8) = 0
runtime.totem.pg.mrp.srp.gather_entered (u64) = 2
runtime.totem.pg.mrp.srp.gather_token_lost (u64) = 0
runtime.totem.pg.mrp.srp.mcast_retx (u64) = 0
runtime.totem.pg.mrp.srp.mcast_rx (u64) = 7289545
runtime.totem.pg.mrp.srp.mcast_tx (u64) = 3270216
runtime.totem.pg.mrp.srp.memb_commit_token_rx (u64) = 4
runtime.totem.pg.mrp.srp.memb_commit_token_tx (u64) = 4
runtime.totem.pg.mrp.srp.memb_join_rx (u64) = 5
runtime.totem.pg.mrp.srp.memb_join_tx (u64) = 3
runtime.totem.pg.mrp.srp.memb_merge_detect_rx (u64) = 79841194
runtime.totem.pg.mrp.srp.memb_merge_detect_tx (u64) = 79841194
runtime.totem.pg.mrp.srp.members.1.config_version (u64) = 0
runtime.totem.pg.mrp.srp.members.1.ip (str) = r(0) ip(192.168.157.10)
runtime.totem.pg.mrp.srp.members.1.join_count (u32) = 1
runtime.totem.pg.mrp.srp.members.1.status (str) = joined
runtime.totem.pg.mrp.srp.members.2.config_version (u64) = 0
runtime.totem.pg.mrp.srp.members.2.ip (str) = r(0) ip(192.168.157.11)
runtime.totem.pg.mrp.srp.members.2.join_count (u32) = 1
runtime.totem.pg.mrp.srp.members.2.status (str) = joined
runtime.totem.pg.mrp.srp.mtt_rx_token (u32) = 199
runtime.totem.pg.mrp.srp.operational_entered (u64) = 2
runtime.totem.pg.mrp.srp.operational_token_lost (u64) = 0
runtime.totem.pg.mrp.srp.orf_token_rx (u64) = 171676165
runtime.totem.pg.mrp.srp.orf_token_tx (u64) = 2
runtime.totem.pg.mrp.srp.recovery_entered (u64) = 2
runtime.totem.pg.mrp.srp.recovery_token_lost (u64) = 0
runtime.totem.pg.mrp.srp.rx_msg_dropped (u64) = 0
runtime.totem.pg.mrp.srp.token_hold_cancel_rx (u64) = 2484729
runtime.totem.pg.mrp.srp.token_hold_cancel_tx (u64) = 868163
runtime.totem.pg.msg_queue_avail (u32) = 0
runtime.totem.pg.msg_reserved (u32) = 1
runtime.votequorum.ev_barrier (u32) = 2
runtime.votequorum.highest_node_id (u32) = 2
runtime.votequorum.lowest_node_id (u32) = 1
runtime.votequorum.this_node_id (u32) = 1
runtime.votequorum.two_node (u8) = 1
runtime.votequorum.wait_for_all_status (u8) = 0
totem.clear_node_high_bit (str) = yes
totem.cluster_name (str) = hana_cluster
totem.consensus (u32) = 6000
totem.crypto_cipher (str) = aes256
totem.crypto_hash (str) = sha1
totem.interface.0.bindnetaddr (str) = 192.168.157.10
totem.interface.0.mcastaddr (str) = 239.192.100.25
totem.interface.0.mcastport (u16) = 5405
totem.interface.0.ttl (u8) = 1
totem.join (u32) = 60
totem.max_messages (u32) = 20
totem.secauth (str) = on
totem.token (u32) = 5000
totem.token_retransmits_before_loss_const (u32) = 10
totem.transport (str) = udpu
totem.version (u32) = 2
uidgid.gid.90 (u8) = 1"""

[[commands]]
matches = "something"
output = "something"
